#=
Download the cached 1/4° moist baroclinic wave initial-condition artifact
from Dropbox.

  atmosphere_ic_quarter_degree.jld2  ≈ ?? GB

The file is the input for the `initial_conditions_path` keyword of
`GordonBell25.moist_baroclinic_wave_model`. It is initially a stand-in
generated by `simulations/generate_analytic_atmosphere_ic.jl` (analytic
IC, no spin-up); once a real spin-up checkpoint is ready it will be
swapped in at the same Dropbox path with no code changes here.

The file is written to `simulations/initial_conditions/` next to this
script and is skipped if already present.

Run:
    julia --project -O0 simulations/download_atmosphere_ic_artifact.jl
=#

using Downloads

const ARTIFACT_NAME = "atmosphere_ic_quarter_degree.jld2"
# TODO: replace with the real Dropbox direct-download URL once the artifact
# has been uploaded. The URL must end in `dl=1` to force a direct download.
const ARTIFACT_URL  = "https://www.dropbox.com/scl/fi/PLACEHOLDER/atmosphere_ic_quarter_degree.jld2?dl=1"

function download_artifact_if_missing(name::AbstractString, url::AbstractString, dest_dir::AbstractString)
    mkpath(dest_dir)
    dest = joinpath(dest_dir, name)
    if isfile(dest)
        @info "$name already present at $dest — skipping"
        return dest
    end
    @info "Downloading $name from $url"
    Downloads.download(url, dest)
    @info "Downloaded $name → $dest ($(filesize(dest)) bytes)"
    return dest
end

function main()
    dest_dir = joinpath(@__DIR__, "initial_conditions")
    download_artifact_if_missing(ARTIFACT_NAME, ARTIFACT_URL, dest_dir)
    return nothing
end

main()
