name: "Compile"

on:
  pull_request:
    paths:
      - '.github/workflows/Compile.yml'
      - '.github/workflows/CompileOrRun.yml'
      - 'simulations/baroclinic_instability_simulation_compile.jl'
      - 'simulations/ocean_climate_simulation_compile.jl'
      - 'Project.toml'
      - 'src/**'
  push:
    branches:
      - main
      - release-*
    tags: '*'
    paths:
      - '.github/workflows/Compile.yml'
      - '.github/workflows/CompileOrRun.yml'
      - 'simulations/baroclinic_instability_simulation_compile.jl'
      - 'simulations/ocean_climate_simulation_compile.jl'
      - 'Project.toml'
      - 'src/**'
  workflow_dispatch:
  schedule:
    - cron: '12 07,19 * * *'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  compile_simulations:
    name: Julia ${{ matrix.julia_version }} - ${{ matrix.sim_type }} - ${{ matrix.os }} - ${{ matrix.xla_runtime }}
    strategy:
      fail-fast: false
      matrix:
        sim_type:
          - 'baroclinic_instability'
          - 'ocean_climate'
        julia_version:
          - '1.11'
        os:
          - ubuntu-24.04
          # - ubuntu-22.04-arm
        xla_runtime:
          - 'IFRT'
    uses: ./.github/workflows/CompileOrRun.yml
    with:
      sim_type: ${{ matrix.sim_type }}
      grid_name: ${{ matrix.sim_type == 'baroclinic_instability' && 'simple_lat_lon' || 'gaussian_islands' }}
      julia_version: ${{ matrix.julia_version }}
      os: ${{ matrix.os }}
      xla_runtime: ${{ matrix.xla_runtime }}
      compile_or_run: 'compile'
      earlyoom_threshold: 4
      julia_optlevel: 0
