name: "Run"

on:
  pull_request:
    paths:
      - '.github/workflows/Run.yml'
      - '.github/workflows/CompileOrRun.yml'
      - 'sharding/sharded_baroclinic_instability_simulation_run.jl'
      - 'simulations/baroclinic_instability_simulation_run.jl'
      - 'simulations/ocean_climate_simulation_run.jl'
      - 'Project.toml'
      - 'src/**'
  push:
    branches:
      - main
      - release-*
    tags: '*'
    paths:
      - '.github/workflows/Run.yml'
      - '.github/workflows/CompileOrRun.yml'
      - 'sharding/sharded_baroclinic_instability_simulation_run.jl'
      - 'simulations/baroclinic_instability_simulation_run.jl'
      - 'simulations/ocean_climate_simulation_run.jl'
      - 'Project.toml'
      - 'src/**'
  workflow_dispatch:
  schedule:
    - cron: '12 07,19 * * *'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  run_simulations:
    name: Serial - Julia ${{ matrix.julia_version }} - ${{ matrix.sim_type }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        sim_type:
          - 'baroclinic_instability'
          - 'ocean_climate'
        julia_version:
          - '1.11'
        os:
          - 'ubuntu-24.04'
          - 'ubuntu-22.04-arm'
    uses: ./.github/workflows/CompileOrRun.yml
    with:
      sim_type: ${{ matrix.sim_type }}
      grid_type: ${{ matrix.sim_type == 'baroclinic_instability' && 'simple_lat_lon' || 'gaussian_islands' }}
      sharded: false
      run_dir: 'simulations'
      julia_version: ${{ matrix.julia_version }}
      os: ${{ matrix.os }}
      xla_runtime: 'IFRT'
      compile_or_run: 'run'
      earlyoom_threshold: 4
      julia_optlevel: 0

  run_sharded:
    name: Sharded - Julia ${{ matrix.julia_version }} - ${{ matrix.grid_type }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: ['ubuntu-24.04', 'ubuntu-22.04-arm']
          grid_type: ['simple_lat_lon']
    uses: ./.github/workflows/CompileOrRun.yml
    with:
      sim_type: 'sharded_baroclinic_instability'
      grid_type: ${{ matrix.grid_type }}
      sharded: true
      run_dir: 'sharding'
      julia_version: '1.11'
      os: ${{ matrix.os }}
      xla_runtime: 'IFRT'
      compile_or_run: 'run'
      earlyoom_threshold: 2
      julia_optlevel: 0
